version: '3.8'

services:
  php:
    build: 
    #volumes:
      #- .:/var/www/html
      context: .
      dockerfile: DockerFile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    #networks:
    #  - my_network
    #depends_on:
    #  - db
    #entrypoint: ["sh", "-c", "sleep 10 && composer install && php-fpm"]
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "60:60"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
      #- ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    #networks:
    #  - my_network


  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "abc" 
      MYSQL_DATABASE: cookBook
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    #networks:
    #  - my_network

#networks:
  #my_network:
  #symfony_network:
  #  driver: bridge

volumes:
  db_data:
  
